### ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
### 01-B | simulation > backward_elimination
### (3)  | linear-top10control.R
### ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
### written by
### ---
### Jinwoo Lee & Maria Pak
### SNU Connectome Lab
### ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

library(grf)
library(ggplot2)

### _______________________________________________________________________ ####
### @@@ PART I. DEFAULT SETTING @@@ ####
## > I-1. Data Preparation ####
# assume we have simulation data using ../train_data_simulation.R.
data <- read.csv("../data/train_lin_weak.csv") 

Y <- data$y
W <- data$w
X <- subset(data, select = -c(y, theta, w, src_subject_id, site_id_l)) # total 149 covariates
site_id_l <- as.factor(data$site_id_l)                                 # for clustering variable

## > I-2. Random Seeds ####
n.seeds <- 5
n.trees <- 2000

# for reproduction using seeds below
seeds <- c(6406, 1553, 2976, 4302, 5960) # generated by 'sample(1:10000, size = n.seeds, replace = FALSE)'


### _______________________________________________________________________ ####
### @@@ PART II. MODEL FITTING @@@ ####
thr.seed.list <- list()

## > II-1. Fitting 'Small' Models Iteratively ####
for (seed_idx in c(1:length(seeds))) {
  current.cf.thr.seed <- causal_forest(X, Y, W, 
                                       Y.hat = NULL, W.hat = NULL,
                                       clusters = site_id_l,   # clustering variable
                                       tune.parameters = "all",
                                       compute.oob.predictions = FALSE,
                                       num.trees = n.trees,
                                       num.threads = 12,
                                       seed = seeds[seed_idx])
  
  thr.seed.list[[paste0("cf.thr.seed", seed_idx)]] = current.cf.thr.seed
}

## > II-2. Performing Seed Ensemble and Making a "Big" Model ####
big.model <- merge_forests(thr.seed.list, compute.oob.predictions = TRUE)

## > II-3. Identifying Key Moderators based on top 10% of VarImp ####
df.varimp <- data.frame(
  cov = colnames(X),
  varimp = variable_importance(big.model)
)

top10.threshold <- quantile(df.varimp$varimp, probs = 0.9)
selected <- df.varimp[df.varimp$varimp >= top10.threshold, "cov"]


### _______________________________________________________________________ ####
### @@@ PART IV. PERFORMANCE EVALUATION @@@ ####
## > IV-1. Evaluating Variable Selection ####
hte_factors <- c('smri_vol_scs_amygdalarh', 'smri_vol_cdk_cdacaterh', 'smri_vol_cdk_parahpallh') # real variables generating HTE
all_variables <- names(data)[-c(1:4, 19)] # except for "y", "theta", "w", "src_subject_id", "site_id_l"

TP <- sum(selected %in% hte_factors)
FP <- sum(selected %in% setdiff(selected, hte_factors))
FN <- sum(hte_factors %in% setdiff(hte_factors, selected))
TN <- length(setdiff(all_variables, union(hte_factors, selected)))

PRE <- TP / (TP + FP)
REC <- TP / (TP + FN)

F1_score <- 2 * PRE * REC / (PRE + REC)

## > IV-4. Final Report ####
print(paste0("[Vars Selection] Top10 heuristic identifies real HTE moderators with F1 = ", round(F1_score, 3)))


### _______________________________________________________________________ ####
### @@@ PART V. VISUALIZATION @@@ ####
## > V-1. Confusion Matrix ####
data.conf <- data.frame(
  Prediction = rep(c("Positive", "Negative"), each = 2),
  Actual = rep(c("Positive", "Negative"), 2),
  Count = c(TP, FN, FP, TN)
)

data.conf$ratio <- c(
  round(TP / (TP + FN), 3),
  round(FN / (TP + FN), 3),
  round(FP / (FP + TN), 3),
  round(TN / (FP + TN), 3)
)

fig3a.lin.top10 <- ggplot(data.conf, aes(x = Actual, y = Prediction, fill = ratio)) +
  geom_tile(color = "white", linewidth = 1.2) +
  geom_text(aes(label = ratio), size = 6, color = "black", fontface = "bold") +
  scale_fill_gradient(low = "white", high = "#0868AC") +
  labs(
    title = "Confusion Matrix",
    x = "Actual",
    y = "Predicted"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    panel.grid = element_blank()
  )